on:
  push:

jobs:
  cleanup-code:
    runs-on: ubuntu-latest

    steps:
    - name : Check Out
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.301

    - name: Install ReSharper
      run: dotnet tool install --global JetBrains.ReSharper.GlobalTools

    - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.4

    - name: Cleanup all changed Code
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
          jb cleanupcode $file
        done

    - name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
    
    - name: Commit changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -a -m 'Automated dotnet-format update
        Co-authored-by: ${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.id }}+${{ github.event.pull_request.user.login }}@users.noreply.github.com>'

    - name: Push changes
      if: steps.git-check.outputs.modified == 'true'
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
