name: SelfTest

on:
  push:
  
jobs:
  self-test:
    runs-on: ubuntu-latest
    name: Self Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: florius0/resharper-ci@v0.2.1
        id: test
        with:
          solution: "./Example1/Example1.sln"
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: resharper-inspection
          path: |
            inspection.xml
            inspection.txt
